Repository cbpudding/link-all-the-languages, pull requests merged in 2019-12, with the labels that each got.

#4 Complete rewrite plus add Zig example
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  include/functions.h
  src/functions.h
  src/hello.rs
  src/lib.c
  src/lib.cpp
  src/lib.rs
  src/lib.zig
  src/main.c
Labels: Yet another language!

#6 Remove dependence on build order
  Makefile
Labels: Patch

#8 New build system!
  build.py
  run.sh
  src/functions.h
  src/main.c
Labels: Improvement

#9 Add Carp
  Makefile
  build.py
  src/functions.h
  src/lib.carp
Labels: New Language

#12 Ordered the functions alphabetically
  Makefile
  build.py
  src/functions.h
Labels: Improvement

#10 Add basic README
  README.md
Labels: Improvement

#14 Add nim
  Makefile
  README.md
  build.py
  src/functions.h
  src/lib.nim
Labels: New Language
